---
title: Marina Robson.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
highlighter: rouge
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
